export const ADD_EVENT = 'ADD_EVENT'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const TOGGLE_LIKED = 'TOGGLE_LIKED'
export const SELECT_EVENT = 'SELECT_EVENT'
export const MOVE_UP = 'MOVE_UP'
export const MOVE_DOWN = 'MOVE_DOWN'
